// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConsoleLog(arg1, arg2, arg3) {
  return window['go']['utils']['Utils']['ConsoleLog'](arg1, arg2, arg3);
}

export function GetLogger() {
  return window['go']['utils']['Utils']['GetLogger']();
}

export function Startup() {
  return window['go']['utils']['Utils']['Startup']();
}
