// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {glg} from '../models';

export function ConsoleLog(arg1:string):Promise<void>;

export function GetLogger():Promise<glg.Glg>;

export function Startup():Promise<void>;
