// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';
import {glg} from '../models';

export function ConsoleLog(arg1:utils.LogLevel,arg2:string,arg3:Array<any>):Promise<void>;

export function GetLogger():Promise<glg.Glg>;

export function Startup():Promise<void>;
